2025-04-01 15:17:29 CST [1]: [3-1] user=,db=,app=,client= LOG:  starting PostgreSQL 15.12 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
2025-04-01 15:17:29 CST [1]: [4-1] user=,db=,app=,client= LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-04-01 15:17:29 CST [1]: [5-1] user=,db=,app=,client= LOG:  listening on IPv6 address "::", port 5432
2025-04-01 15:17:30 CST [1]: [6-1] user=,db=,app=,client= LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-04-01 15:17:30 CST [30]: [1-1] user=,db=,app=,client= LOG:  database system was interrupted; last known up at 2025-04-01 14:59:07 CST
2025-04-01 15:17:41 CST [30]: [2-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 10.08 s, current path: ./base/1/2617_vm
2025-04-01 15:17:51 CST [30]: [3-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 20.04 s, current path: ./base/1/3380
2025-04-01 15:18:01 CST [30]: [4-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 30.09 s, current path: ./base/16384/2603_vm
2025-04-01 15:18:11 CST [30]: [5-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 40.04 s, current path: ./base/16384/3712
2025-04-01 15:18:21 CST [30]: [6-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 50.03 s, current path: ./base/4/2674
2025-04-01 15:18:31 CST [30]: [7-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 60.04 s, current path: ./base/5/1249_fsm
2025-04-01 15:18:41 CST [30]: [8-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 70.01 s, current path: ./base/5/3596
2025-04-01 15:18:51 CST [30]: [9-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 80.29 s, current path: ./pg_multixact/members/0000
2025-04-01 15:18:53 CST [30]: [10-1] user=,db=,app=,client= LOG:  database system was not properly shut down; automatic recovery in progress
2025-04-01 15:18:53 CST [30]: [11-1] user=,db=,app=,client= LOG:  redo starts at 0/197F3A8
2025-04-01 15:18:53 CST [30]: [12-1] user=,db=,app=,client= LOG:  invalid record length at 0/197F490: wanted 24, got 0
2025-04-01 15:18:53 CST [30]: [13-1] user=,db=,app=,client= LOG:  redo done at 0/197F458 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.02 s
2025-04-01 15:18:53 CST [28]: [1-1] user=,db=,app=,client= LOG:  checkpoint starting: end-of-recovery immediate wait
2025-04-01 15:18:55 CST [28]: [2-1] user=,db=,app=,client= LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.235 s, sync=0.321 s, total=1.419 s; sync files=2, longest=0.184 s, average=0.161 s; distance=0 kB, estimate=0 kB
2025-04-01 15:18:55 CST [1]: [7-1] user=,db=,app=,client= LOG:  database system is ready to accept connections
2025-04-01 17:29:12 CST [1]: [8-1] user=,db=,app=,client= LOG:  received fast shutdown request
2025-04-01 17:29:12 CST [1]: [9-1] user=,db=,app=,client= LOG:  aborting any active transactions
2025-04-01 17:29:12 CST [1]: [10-1] user=,db=,app=,client= LOG:  background worker "logical replication launcher" (PID 33) exited with exit code 1
2025-04-01 17:29:12 CST [28]: [3-1] user=,db=,app=,client= LOG:  shutting down
2025-04-01 17:29:12 CST [28]: [4-1] user=,db=,app=,client= LOG:  checkpoint starting: shutdown immediate
2025-04-01 17:29:14 CST [28]: [5-1] user=,db=,app=,client= LOG:  checkpoint complete: wrote 0 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.321 s, sync=0.001 s, total=1.937 s; sync files=0, longest=0.000 s, average=0.000 s; distance=0 kB, estimate=0 kB
2025-04-01 17:29:14 CST [1]: [11-1] user=,db=,app=,client= LOG:  database system is shut down
