2025-03-28 17:26:50 CST [1]: [3-1] user=,db=,app=,client= LOG:  starting PostgreSQL 15.12 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
2025-03-28 17:26:50 CST [1]: [4-1] user=,db=,app=,client= LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-03-28 17:26:50 CST [1]: [5-1] user=,db=,app=,client= LOG:  listening on IPv6 address "::", port 5432
2025-03-28 17:26:51 CST [1]: [6-1] user=,db=,app=,client= LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-03-28 17:26:52 CST [30]: [1-1] user=,db=,app=,client= LOG:  database system was interrupted; last known up at 2025-03-28 13:32:03 CST
2025-03-28 17:27:03 CST [30]: [2-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 10.05 s, current path: ./base/1/2606_fsm
2025-03-28 17:27:13 CST [30]: [3-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 20.04 s, current path: ./base/1/2665
2025-03-28 17:27:23 CST [30]: [4-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 30.12 s, current path: ./base/1/3576
2025-03-28 17:27:33 CST [30]: [5-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 40.03 s, current path: ./base/16384/2680
2025-03-28 17:27:43 CST [30]: [6-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 50.06 s, current path: ./base/4/2602
2025-03-28 17:27:53 CST [30]: [7-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 60.02 s, current path: ./base/4/2841
2025-03-28 17:28:03 CST [30]: [8-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 70.05 s, current path: ./base/5/2657
2025-03-28 17:28:13 CST [30]: [9-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 80.25 s, current path: ./global/1260
2025-03-28 17:28:23 CST [30]: [10-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 90.20 s, current path: ./log/postgresql-2025-03-10_115946.log
2025-03-28 17:28:30 CST [30]: [11-1] user=,db=,app=,client= LOG:  database system was not properly shut down; automatic recovery in progress
2025-03-28 17:28:30 CST [30]: [12-1] user=,db=,app=,client= LOG:  redo starts at 0/197E4A0
2025-03-28 17:28:30 CST [30]: [13-1] user=,db=,app=,client= LOG:  invalid record length at 0/197E588: wanted 24, got 0
2025-03-28 17:28:30 CST [30]: [14-1] user=,db=,app=,client= LOG:  redo done at 0/197E550 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.19 s
2025-03-28 17:28:31 CST [28]: [1-1] user=,db=,app=,client= LOG:  checkpoint starting: end-of-recovery immediate wait
2025-03-28 17:28:31 CST [28]: [2-1] user=,db=,app=,client= LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.134 s, sync=0.078 s, total=0.860 s; sync files=2, longest=0.067 s, average=0.039 s; distance=0 kB, estimate=0 kB
2025-03-28 17:28:32 CST [1]: [7-1] user=,db=,app=,client= LOG:  database system is ready to accept connections
2025-03-28 18:34:47 CST [1]: [8-1] user=,db=,app=,client= LOG:  received fast shutdown request
2025-03-28 18:34:48 CST [1]: [9-1] user=,db=,app=,client= LOG:  aborting any active transactions
2025-03-28 18:34:48 CST [1]: [10-1] user=,db=,app=,client= LOG:  background worker "logical replication launcher" (PID 33) exited with exit code 1
2025-03-28 18:34:48 CST [28]: [3-1] user=,db=,app=,client= LOG:  shutting down
2025-03-28 18:34:48 CST [28]: [4-1] user=,db=,app=,client= LOG:  checkpoint starting: shutdown immediate
2025-03-28 18:34:50 CST [28]: [5-1] user=,db=,app=,client= LOG:  checkpoint complete: wrote 0 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.334 s, sync=0.001 s, total=1.579 s; sync files=0, longest=0.000 s, average=0.000 s; distance=0 kB, estimate=0 kB
2025-03-28 18:34:50 CST [1]: [11-1] user=,db=,app=,client= LOG:  database system is shut down
