2025-03-28 10:18:29 CST [1]: [3-1] user=,db=,app=,client= LOG:  starting PostgreSQL 15.12 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
2025-03-28 10:18:29 CST [1]: [4-1] user=,db=,app=,client= LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-03-28 10:18:29 CST [1]: [5-1] user=,db=,app=,client= LOG:  listening on IPv6 address "::", port 5432
2025-03-28 10:18:30 CST [1]: [6-1] user=,db=,app=,client= LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-03-28 10:18:32 CST [30]: [1-1] user=,db=,app=,client= LOG:  database system was interrupted; last known up at 2025-03-27 09:43:01 CST
2025-03-28 10:18:43 CST [30]: [2-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 10.09 s, current path: ./base/1/2600
2025-03-28 10:18:53 CST [30]: [3-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 20.28 s, current path: ./base/1/2612
2025-03-28 10:19:03 CST [30]: [4-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 30.27 s, current path: ./base/1/2673
2025-03-28 10:19:13 CST [30]: [5-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 40.24 s, current path: ./base/1/3085
2025-03-28 10:19:23 CST [30]: [6-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 50.01 s, current path: ./base/1/4144
2025-03-28 10:19:33 CST [30]: [7-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 60.15 s, current path: ./base/16384/13441_vm
2025-03-28 10:19:43 CST [30]: [8-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 70.05 s, current path: ./base/16384/2687
2025-03-28 10:19:53 CST [30]: [9-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 80.00 s, current path: ./base/16384/3541_fsm
2025-03-28 10:20:03 CST [30]: [10-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 90.00 s, current path: ./base/4/13436_fsm
2025-03-28 10:20:13 CST [30]: [11-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 100.10 s, current path: ./base/4/2701
2025-03-28 10:20:23 CST [30]: [12-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 110.04 s, current path: ./base/4/4164
2025-03-28 10:20:33 CST [30]: [13-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 120.04 s, current path: ./base/5/2607
2025-03-28 10:20:44 CST [30]: [14-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 131.63 s, current path: ./base/5/2660
2025-03-28 10:20:53 CST [30]: [15-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 140.04 s, current path: ./base/5/3079
2025-03-28 10:21:03 CST [30]: [16-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 150.03 s, current path: ./base/5/3602_vm
2025-03-28 10:21:13 CST [30]: [17-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 160.19 s, current path: ./base/5/6238
2025-03-28 10:21:23 CST [30]: [18-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 170.11 s, current path: ./global/pg_filenode.map
2025-03-28 10:21:31 CST [30]: [19-1] user=,db=,app=,client= LOG:  database system was not properly shut down; automatic recovery in progress
2025-03-28 10:21:32 CST [30]: [20-1] user=,db=,app=,client= LOG:  redo starts at 0/197E308
2025-03-28 10:21:32 CST [30]: [21-1] user=,db=,app=,client= LOG:  invalid record length at 0/197E340: wanted 24, got 0
2025-03-28 10:21:32 CST [30]: [22-1] user=,db=,app=,client= LOG:  redo done at 0/197E308 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.39 s
2025-03-28 10:21:33 CST [28]: [1-1] user=,db=,app=,client= LOG:  checkpoint starting: end-of-recovery immediate wait
2025-03-28 10:21:37 CST [28]: [2-1] user=,db=,app=,client= LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.247 s, sync=0.430 s, total=5.032 s; sync files=2, longest=0.264 s, average=0.215 s; distance=0 kB, estimate=0 kB
2025-03-28 10:21:39 CST [1]: [7-1] user=,db=,app=,client= LOG:  database system is ready to accept connections
2025-03-28 12:49:10 CST [1]: [8-1] user=,db=,app=,client= LOG:  received fast shutdown request
2025-03-28 12:49:10 CST [1]: [9-1] user=,db=,app=,client= LOG:  aborting any active transactions
2025-03-28 12:49:10 CST [1]: [10-1] user=,db=,app=,client= LOG:  background worker "logical replication launcher" (PID 33) exited with exit code 1
2025-03-28 12:49:10 CST [28]: [3-1] user=,db=,app=,client= LOG:  shutting down
2025-03-28 12:49:10 CST [28]: [4-1] user=,db=,app=,client= LOG:  checkpoint starting: shutdown immediate
2025-03-28 12:49:12 CST [28]: [5-1] user=,db=,app=,client= LOG:  checkpoint complete: wrote 0 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.358 s, sync=0.001 s, total=1.746 s; sync files=0, longest=0.000 s, average=0.000 s; distance=0 kB, estimate=0 kB
2025-03-28 12:49:12 CST [1]: [11-1] user=,db=,app=,client= LOG:  database system is shut down
